[deps]
Debugger = "31a5f54b-26ea-5ae9-a837-f05ce5417438"
LanguageServer = "2b0e0bc5-e4fd-59b4-8912-456d1b03d8d7"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
StaticLint = "b3cc710f-9c33-5bdb-a03d-a94903873e97"
SymbolServer = "cf896787-08d5-524d-9de7-132aaa0cb996"
